init:
  appName: Bitsy
  appPath: $Pwd(./..)
  '!region': $params.region
  '!gcpCredentials': $params.authWith
  gcp: ${secrets.$gcpCredentials}
  projectID: $gcp.ProjectID
  prefix: $Replace(${projectID},'-','_')
  configBucket: ${prefix}_config
  triggerBucket: ${prefix}_bitsy
  opsBucket: ${prefix}_operation

  target:
    URL: ssh://127.0.0.1/
    credentials: localhost

  config: $LoadJSON(config.json)

pipeline:
  deploy:
    setSdk:
      action: sdk:set
      target: $target
      sdk: go:1.15

    build:
      action: exec:run
      target: $target
      sleepTimeMs: 1500
      checkError: true
      commands:
        - cd ${appPath}
        - unset GOPATH
        - go mod vendor
        - go build

    deploy:
      action: gcp/cloudfunctions:deploy
      availableMemoryMb: 4096
      timeout: 540s
      maxInstances: 500
      region: $region
      retry: true
      '@name': $appName
      entryPoint: HandleEvent
      credentials: $gcpCredentials
      environmentVariables:
        CONFIG: $AsJSON($config)
      runtime: go113
      eventTrigger:
        eventType: google.storage.object.finalize
        resource: projects/_/buckets/${triggerBucket}
      source:
        URL: ${appPath}
